{
 "title": "Kafka Lag Exporter1",
 "time": { "from": "now-45m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "All Consumer Group Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumer Group Max Lag Seconds",
   "type": "graph",
   "description": "Max extrapolated lag in seconds for each consumer group.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "estimated lag in seconds" }
   ],
   "targets": [
    {
     "expr": "topk(50, kafka_consumergroup_group_max_lag_seconds)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Consumer Group Max Lag Offsets",
   "type": "graph",
   "description": "Max offset lag for each consumer group.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "offsets" }
   ],
   "targets": [
    {
     "expr": "topk(50, kafka_consumergroup_group_max_lag)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_group_sum_lag",
     "legendFormat": "{{group}}"
    }
   ]
  }
 ]
}